'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Cities', [
      { id: 35, name: 'KEPULAUAN SERIBU', provinceId: 1, createdAt: new Date(), updatedAt: new Date() },
      { id: 36, name: 'JAKARTA UTARA', provinceId: 1, createdAt: new Date(), updatedAt: new Date() },
      { id: 37, name: 'JAKARTA BARAT', provinceId: 1, createdAt: new Date(), updatedAt: new Date() },
      { id: 38, name: 'JAKARTA PUSAT', provinceId: 1, createdAt: new Date(), updatedAt: new Date() },
      { id: 39, name: 'JAKARTA TIMUR', provinceId: 1, createdAt: new Date(), updatedAt: new Date() },
      { id: 40, name: 'JAKARTA SELATAN', provinceId: 1, createdAt: new Date(), updatedAt: new Date() },
      { id: 41, name: 'KOTA TANGERANG', provinceId: 2, createdAt: new Date(), updatedAt: new Date() },
      { id: 42, name: 'TANGERANG', provinceId: 2, createdAt: new Date(), updatedAt: new Date() },
      { id: 43, name: 'TANGERANG SELATAN', provinceId: 2, createdAt: new Date(), updatedAt: new Date() },
      { id: 44, name: 'CILEGON', provinceId: 2, createdAt: new Date(), updatedAt: new Date() },
      { id: 45, name: 'KOTA SERANG', provinceId: 2, createdAt: new Date(), updatedAt: new Date() },
      { id: 46, name: 'LEBAK', provinceId: 2, createdAt: new Date(), updatedAt: new Date() },
      { id: 47, name: 'PANDEGLANG', provinceId: 2, createdAt: new Date(), updatedAt: new Date() },
      { id: 48, name: 'SERANG', provinceId: 2, createdAt: new Date(), updatedAt: new Date() },
      { id: 49, name: 'KOTA DEPOK', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 50, name: 'BEKASI', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 51, name: 'KOTA BEKASI', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 52, name: 'BOGOR', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 53, name: 'KOTA BOGOR', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 54, name: 'CIAMIS', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 55, name: 'CIANJUR', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 56, name: 'CIREBON', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 57, name: 'GARUT', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 58, name: 'INDRAMAYU', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 59, name: 'BANDUNG', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 60, name: 'BANDUNG BARAT', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 61, name: 'KARAWANG', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 62, name: 'KOTA BANDUNG', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 63, name: 'KOTA BANJAR', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 64, name: 'KOTA CIMAHI', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 65, name: 'KOTA CIREBON', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 66, name: 'KOTA SUKABUMI', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 67, name: 'KOTA TASIKMALAYA', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 68, name: 'KUNINGAN', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 69, name: 'MAJALENGKA', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 70, name: 'PANGANDARAN', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 71, name: 'PURWAKARTA', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 72, name: 'SUBANG', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 73, name: 'SUKABUMI', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 74, name: 'SUMEDANG', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 75, name: 'TASIKMALAYA', provinceId: 3, createdAt: new Date(), updatedAt: new Date() },
      { id: 76, name: 'BANJARNEGARA', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 77, name: 'BANYUMAS', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 78, name: 'BATANG', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 79, name: 'BLORA', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 80, name: 'BOYOLALI', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 81, name: 'BREBES', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 82, name: 'CILACAP', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 83, name: 'DEMAK', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 84, name: 'GROBOGAN', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 85, name: 'JEPARA', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 86, name: 'KARANGANYAR', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 87, name: 'KEBUMEN', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 88, name: 'KENDAL', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 89, name: 'KLATEN', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 90, name: 'KOTA MAGELANG', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 91, name: 'KOTA PEKALONGAN', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 92, name: 'KOTA SEMARANG', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 93, name: 'KOTA TEGAL', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 94, name: 'KUDUS', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 95, name: 'MAGELANG', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 96, name: 'PATI', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 97, name: 'PEKALONGAN', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 98, name: 'PEMALANG', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 99, name: 'PURBALINGGA', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 100, name: 'PURWOREJO', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 101, name: 'REMBANG', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 102, name: 'SALATIGA', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 103, name: 'SEMARANG', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 104, name: 'SRAGEN', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 105, name: 'SUKOHARJO', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 106, name: 'SURAKARTA', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 107, name: 'TEGAL', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 108, name: 'TEMANGGUNG', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 109, name: 'WONOGIRI', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 110, name: 'WONOSOBO', provinceId: 4, createdAt: new Date(), updatedAt: new Date() },
      { id: 111, name: 'BANTUL', provinceId: 5, createdAt: new Date(), updatedAt: new Date() },
      { id: 112, name: 'GUNUNG KIDUL', provinceId: 5, createdAt: new Date(), updatedAt: new Date() },
      { id: 113, name: 'KOTA YOGYAKARTA', provinceId: 5, createdAt: new Date(), updatedAt: new Date() },
      { id: 114, name: 'KULON PROGO', provinceId: 5, createdAt: new Date(), updatedAt: new Date() },
      { id: 115, name: 'SLEMAN', provinceId: 5, createdAt: new Date(), updatedAt: new Date() },
      { id: 116, name: 'BANGKALAN', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 117, name: 'BANYUWANGI', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 118, name: 'BATU', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 119, name: 'BLITAR', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 120, name: 'BOJONEGORO', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 121, name: 'BONDOWOSO', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 122, name: 'GRESIK', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 123, name: 'JEMBER', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 124, name: 'JOMBANG', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 125, name: 'KEDIRI', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 126, name: 'KOTA BLITAR', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 127, name: 'KOTA KEDIRI', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 128, name: 'KOTA MADIUN', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 129, name: 'KOTA MALANG', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 130, name: 'KOTA MOJOKERTO', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 131, name: 'KOTA PASURUAN', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 132, name: 'KOTA PROBOLINGGO', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 133, name: 'LAMONGAN', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 134, name: 'LUMAJANG', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 135, name: 'MADIUN', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 136, name: 'MAGETAN', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 137, name: 'MALANG', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 138, name: 'MOJOKERTO', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 139, name: 'NGANJUK', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 140, name: 'NGAWI', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 141, name: 'PACITAN', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 142, name: 'PAMEKASAN', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 143, name: 'PASURUAN', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 144, name: 'PONOROGO', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 145, name: 'PROBOLINGGO', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 146, name: 'SAMPANG', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 147, name: 'SIDOARJO', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 148, name: 'SITUBONDO', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 149, name: 'SUMENEP', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 150, name: 'SURABAYA', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 151, name: 'TRENGGALEK', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 152, name: 'TUBAN', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 153, name: 'TULUNGAGUNG', provinceId: 6, createdAt: new Date(), updatedAt: new Date() },
      { id: 154, name: 'BENGKULU', provinceId: 7, createdAt: new Date(), updatedAt: new Date() },
      { id: 155, name: 'BENGKULU SELATAN', provinceId: 7, createdAt: new Date(), updatedAt: new Date() },
      { id: 156, name: 'BENGKULU TENGAH', provinceId: 7, createdAt: new Date(), updatedAt: new Date() },
      { id: 157, name: 'BENGKULU UTARA', provinceId: 7, createdAt: new Date(), updatedAt: new Date() },
      { id: 158, name: 'KAUR', provinceId: 7, createdAt: new Date(), updatedAt: new Date() },
      { id: 159, name: 'KEPAHIANG', provinceId: 7, createdAt: new Date(), updatedAt: new Date() },
      { id: 160, name: 'LEBONG', provinceId: 7, createdAt: new Date(), updatedAt: new Date() },
      { id: 161, name: 'MUKOMUKO', provinceId: 7, createdAt: new Date(), updatedAt: new Date() },
      { id: 162, name: 'REJANG LEBONG', provinceId: 7, createdAt: new Date(), updatedAt: new Date() },
      { id: 163, name: 'SELUMA', provinceId: 7, createdAt: new Date(), updatedAt: new Date() },
      { id: 164, name: 'ACEH BARAT', provinceId: 8, createdAt: new Date(), updatedAt: new Date() },
      { id: 165, name: 'ACEH BARAT DAYA', provinceId: 8, createdAt: new Date(), updatedAt: new Date() },
      { id: 166, name: 'ACEH BESAR', provinceId: 8, createdAt: new Date(), updatedAt: new Date() },
      { id: 167, name: 'ACEH JAYA', provinceId: 8, createdAt: new Date(), updatedAt: new Date() },
      { id: 168, name: 'ACEH SELATAN', provinceId: 8, createdAt: new Date(), updatedAt: new Date() },
      { id: 169, name: 'ACEH SINGKIL', provinceId: 8, createdAt: new Date(), updatedAt: new Date() },
      { id: 170, name: 'ACEH TAMIANG', provinceId: 8, createdAt: new Date(), updatedAt: new Date() },
      { id: 171, name: 'ACEH TENGAH', provinceId: 8, createdAt: new Date(), updatedAt: new Date() },
      { id: 172, name: 'ACEH TENGGARA', provinceId: 8, createdAt: new Date(), updatedAt: new Date() },
      { id: 173, name: 'ACEH TIMUR', provinceId: 8, createdAt: new Date(), updatedAt: new Date() },
      { id: 174, name: 'ACEH UTARA', provinceId: 8, createdAt: new Date(), updatedAt: new Date() },
      { id: 175, name: 'BANDA ACEH', provinceId: 8, createdAt: new Date(), updatedAt: new Date() },
      { id: 176, name: 'BENER MERIAH', provinceId: 8, createdAt: new Date(), updatedAt: new Date() },
      { id: 177, name: 'BIREUEN', provinceId: 8, createdAt: new Date(), updatedAt: new Date() },
      { id: 178, name: 'GAYO LUES', provinceId: 8, createdAt: new Date(), updatedAt: new Date() },
      { id: 179, name: 'LANGSA', provinceId: 8, createdAt: new Date(), updatedAt: new Date() },
      { id: 180, name: 'LHOKSEUMAWE', provinceId: 8, createdAt: new Date(), updatedAt: new Date() },
      { id: 181, name: 'NAGAN RAYA', provinceId: 8, createdAt: new Date(), updatedAt: new Date() },
      { id: 182, name: 'PIDIE', provinceId: 8, createdAt: new Date(), updatedAt: new Date() },
      { id: 183, name: 'PIDIE JAYA', provinceId: 8, createdAt: new Date(), updatedAt: new Date() },
      { id: 184, name: 'SABANG', provinceId: 8, createdAt: new Date(), updatedAt: new Date() },
      { id: 185, name: 'SIMEULUE', provinceId: 8, createdAt: new Date(), updatedAt: new Date() },
      { id: 186, name: 'SUBULUSSALAM', provinceId: 8, createdAt: new Date(), updatedAt: new Date() },
      { id: 187, name: 'BATANG HARI', provinceId: 9, createdAt: new Date(), updatedAt: new Date() },
      { id: 188, name: 'BUNGO', provinceId: 9, createdAt: new Date(), updatedAt: new Date() },
      { id: 189, name: 'JAMBI', provinceId: 9, createdAt: new Date(), updatedAt: new Date() },
      { id: 190, name: 'KERINCI', provinceId: 9, createdAt: new Date(), updatedAt: new Date() },
      { id: 191, name: 'MERANGIN', provinceId: 9, createdAt: new Date(), updatedAt: new Date() },
      { id: 192, name: 'MUARO JAMBI', provinceId: 9, createdAt: new Date(), updatedAt: new Date() },
      { id: 193, name: 'SAROLANGUN', provinceId: 9, createdAt: new Date(), updatedAt: new Date() },
      { id: 194, name: 'SUNGAI PENUH', provinceId: 9, createdAt: new Date(), updatedAt: new Date() },
      { id: 195, name: 'TANJUNG JABUNG BARAT', provinceId: 9, createdAt: new Date(), updatedAt: new Date() },
      { id: 196, name: 'TANJUNG JABUNG TIMUR', provinceId: 9, createdAt: new Date(), updatedAt: new Date() },
      { id: 197, name: 'TEBO', provinceId: 9, createdAt: new Date(), updatedAt: new Date() },
      { id: 198, name: 'BANGKA', provinceId: 10, createdAt: new Date(), updatedAt: new Date() },
      { id: 199, name: 'BANGKA BARAT', provinceId: 10, createdAt: new Date(), updatedAt: new Date() },
      { id: 200, name: 'BANGKA SELATAN', provinceId: 10, createdAt: new Date(), updatedAt: new Date() },
      { id: 201, name: 'BANGKA TENGAH', provinceId: 10, createdAt: new Date(), updatedAt: new Date() },
      { id: 202, name: 'BELITUNG', provinceId: 10, createdAt: new Date(), updatedAt: new Date() },
      { id: 203, name: 'BELITUNG TIMUR', provinceId: 10, createdAt: new Date(), updatedAt: new Date() },
      { id: 204, name: 'PANGKALPINANG', provinceId: 10, createdAt: new Date(), updatedAt: new Date() },
      { id: 205, name: 'BATAM', provinceId: 11, createdAt: new Date(), updatedAt: new Date() },
      { id: 206, name: 'BINTAN', provinceId: 11, createdAt: new Date(), updatedAt: new Date() },
      { id: 207, name: 'KARIMUN', provinceId: 11, createdAt: new Date(), updatedAt: new Date() },
      { id: 208, name: 'KEPULAUAN ANAMBAS', provinceId: 11, createdAt: new Date(), updatedAt: new Date() },
      { id: 209, name: 'LINGGA', provinceId: 11, createdAt: new Date(), updatedAt: new Date() },
      { id: 210, name: 'NATUNA', provinceId: 11, createdAt: new Date(), updatedAt: new Date() },
      { id: 211, name: 'TANJUNGPINANG', provinceId: 11, createdAt: new Date(), updatedAt: new Date() },
      { id: 212, name: 'BANDAR LAMPUNG', provinceId: 12, createdAt: new Date(), updatedAt: new Date() },
      { id: 213, name: 'LAMPUNG BARAT', provinceId: 12, createdAt: new Date(), updatedAt: new Date() },
      { id: 214, name: 'LAMPUNG SELATAN', provinceId: 12, createdAt: new Date(), updatedAt: new Date() },
      { id: 215, name: 'LAMPUNG TENGAH', provinceId: 12, createdAt: new Date(), updatedAt: new Date() },
      { id: 216, name: 'LAMPUNG TIMUR', provinceId: 12, createdAt: new Date(), updatedAt: new Date() },
      { id: 217, name: 'LAMPUNG UTARA', provinceId: 12, createdAt: new Date(), updatedAt: new Date() },
      { id: 218, name: 'MESUJI', provinceId: 12, createdAt: new Date(), updatedAt: new Date() },
      { id: 219, name: 'METRO', provinceId: 12, createdAt: new Date(), updatedAt: new Date() },
      { id: 220, name: 'PESAWARAN', provinceId: 12, createdAt: new Date(), updatedAt: new Date() },
      { id: 221, name: 'PESISIR BARAT', provinceId: 12, createdAt: new Date(), updatedAt: new Date() },
      { id: 222, name: 'PRINGSEWU', provinceId: 12, createdAt: new Date(), updatedAt: new Date() },
      { id: 223, name: 'TANGGAMUS', provinceId: 12, createdAt: new Date(), updatedAt: new Date() },
      { id: 224, name: 'TULANG BAWANG BARAT', provinceId: 12, createdAt: new Date(), updatedAt: new Date() },
      { id: 225, name: 'TULANGBAWANG', provinceId: 12, createdAt: new Date(), updatedAt: new Date() },
      { id: 226, name: 'WAY KANAN', provinceId: 12, createdAt: new Date(), updatedAt: new Date() },
      { id: 227, name: 'BENGKALIS', provinceId: 13, createdAt: new Date(), updatedAt: new Date() },
      { id: 228, name: 'DUMAI', provinceId: 13, createdAt: new Date(), updatedAt: new Date() },
      { id: 229, name: 'INDRAGIRI HILIR', provinceId: 13, createdAt: new Date(), updatedAt: new Date() },
      { id: 230, name: 'INDRAGIRI HULU', provinceId: 13, createdAt: new Date(), updatedAt: new Date() },
      { id: 231, name: 'KAMPAR', provinceId: 13, createdAt: new Date(), updatedAt: new Date() },
      { id: 232, name: 'KEPULAUAN MERANTI', provinceId: 13, createdAt: new Date(), updatedAt: new Date() },
      { id: 233, name: 'KUANTAN SINGINGI', provinceId: 13, createdAt: new Date(), updatedAt: new Date() },
      { id: 234, name: 'PEKANBARU', provinceId: 13, createdAt: new Date(), updatedAt: new Date() },
      { id: 235, name: 'PELALAWAN', provinceId: 13, createdAt: new Date(), updatedAt: new Date() },
      { id: 236, name: 'ROKAN HILIR', provinceId: 13, createdAt: new Date(), updatedAt: new Date() },
      { id: 237, name: 'ROKAN HULU', provinceId: 13, createdAt: new Date(), updatedAt: new Date() },
      { id: 238, name: 'SIAK', provinceId: 13, createdAt: new Date(), updatedAt: new Date() },
      { id: 239, name: 'AGAM', provinceId: 14, createdAt: new Date(), updatedAt: new Date() },
      { id: 240, name: 'BUKITTINGGI', provinceId: 14, createdAt: new Date(), updatedAt: new Date() },
      { id: 241, name: 'DHARMASRAYA', provinceId: 14, createdAt: new Date(), updatedAt: new Date() },
      { id: 242, name: 'KEPULAUAN MENTAWAI', provinceId: 14, createdAt: new Date(), updatedAt: new Date() },
      { id: 243, name: 'KOTA SOLOK', provinceId: 14, createdAt: new Date(), updatedAt: new Date() },
      { id: 244, name: 'LIMA PULUH KOTA', provinceId: 14, createdAt: new Date(), updatedAt: new Date() },
      { id: 245, name: 'PADANG', provinceId: 14, createdAt: new Date(), updatedAt: new Date() },
      { id: 246, name: 'PADANG PANJANG', provinceId: 14, createdAt: new Date(), updatedAt: new Date() },
      { id: 247, name: 'PADANG PARIAMAN', provinceId: 14, createdAt: new Date(), updatedAt: new Date() },
      { id: 248, name: 'PARIAMAN', provinceId: 14, createdAt: new Date(), updatedAt: new Date() },
      { id: 249, name: 'PASAMAN', provinceId: 14, createdAt: new Date(), updatedAt: new Date() },
      { id: 250, name: 'PASAMAN BARAT', provinceId: 14, createdAt: new Date(), updatedAt: new Date() },
      { id: 251, name: 'PAYAKUMBUH', provinceId: 14, createdAt: new Date(), updatedAt: new Date() },
      { id: 252, name: 'PESISIR SELATAN', provinceId: 14, createdAt: new Date(), updatedAt: new Date() },
      { id: 253, name: 'SAWAHLUNTO', provinceId: 14, createdAt: new Date(), updatedAt: new Date() },
      { id: 254, name: 'SIJUNJUNG', provinceId: 14, createdAt: new Date(), updatedAt: new Date() },
      { id: 255, name: 'SOLOK', provinceId: 14, createdAt: new Date(), updatedAt: new Date() },
      { id: 256, name: 'SOLOK SELATAN', provinceId: 14, createdAt: new Date(), updatedAt: new Date() },
      { id: 257, name: 'TANAH DATAR', provinceId: 14, createdAt: new Date(), updatedAt: new Date() },
      { id: 258, name: 'BANYU ASIN', provinceId: 15, createdAt: new Date(), updatedAt: new Date() },
      { id: 259, name: 'EMPAT LAWANG', provinceId: 15, createdAt: new Date(), updatedAt: new Date() },
      { id: 260, name: 'LAHAT', provinceId: 15, createdAt: new Date(), updatedAt: new Date() },
      { id: 261, name: 'LUBUKLINGGAU', provinceId: 15, createdAt: new Date(), updatedAt: new Date() },
      { id: 262, name: 'MUARA ENIM', provinceId: 15, createdAt: new Date(), updatedAt: new Date() },
      { id: 263, name: 'MUSI BANYUASIN', provinceId: 15, createdAt: new Date(), updatedAt: new Date() },
      { id: 264, name: 'MUSI RAWAS', provinceId: 15, createdAt: new Date(), updatedAt: new Date() },
      { id: 265, name: 'MUSI RAWAS UTARA', provinceId: 15, createdAt: new Date(), updatedAt: new Date() },
      { id: 266, name: 'OGAN ILIR', provinceId: 15, createdAt: new Date(), updatedAt: new Date() },
      { id: 267, name: 'OGAN KOMERING ILIR', provinceId: 15, createdAt: new Date(), updatedAt: new Date() },
      { id: 268, name: 'OGAN KOMERING ULU', provinceId: 15, createdAt: new Date(), updatedAt: new Date() },
      { id: 269, name: 'OGAN KOMERING ULU SELATAN', provinceId: 15, createdAt: new Date(), updatedAt: new Date() },
      { id: 270, name: 'OGAN KOMERING ULU TIMUR', provinceId: 15, createdAt: new Date(), updatedAt: new Date() },
      { id: 271, name: 'PAGAR ALAM', provinceId: 15, createdAt: new Date(), updatedAt: new Date() },
      { id: 272, name: 'PALEMBANG', provinceId: 15, createdAt: new Date(), updatedAt: new Date() },
      { id: 273, name: 'PENUKAL ABAB LEMATANG ILIR', provinceId: 15, createdAt: new Date(), updatedAt: new Date() },
      { id: 274, name: 'PRABUMULIH', provinceId: 15, createdAt: new Date(), updatedAt: new Date() },
      { id: 275, name: 'ASAHAN', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 276, name: 'BATU BARA', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 277, name: 'DAIRI', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 278, name: 'DELI SERDANG', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 279, name: 'GUNUNGSITOLI', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 280, name: 'HUMBANG HASUNDUTAN', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 281, name: 'KARO', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 282, name: 'KOTA BINJAI', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 283, name: 'KOTA MEDAN', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 284, name: 'KOTA TANJUNGBALAI', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 285, name: 'LABUHANBATU', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 286, name: 'LABUHANBATU SELATAN', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 287, name: 'LABUHANBATU UTARA', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 288, name: 'LANGKAT', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 289, name: 'MANDAILING NATAL', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 290, name: 'NIAS', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 291, name: 'NIAS BARAT', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 292, name: 'NIAS SELATAN', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 293, name: 'NIAS UTARA', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 294, name: 'PADANG LAWAS', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 295, name: 'PADANG LAWAS UTARA', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 296, name: 'PADANGSIDIMPUAN', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 297, name: 'PAKPAK BARAT', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 298, name: 'PEMATANGSIANTAR', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 299, name: 'SAMOSIR', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 300, name: 'SERDANG BEDAGAI', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 301, name: 'SIBOLGA', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 302, name: 'SIMALUNGUN', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 303, name: 'TAPANULI SELATAN', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 304, name: 'TAPANULI TENGAH', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 305, name: 'TAPANULI UTARA', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 306, name: 'TEBINGTINGGI', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 307, name: 'TOBA SAMOSIR', provinceId: 16, createdAt: new Date(), updatedAt: new Date() },
      { id: 308, name: 'BENGKAYANG', provinceId: 17, createdAt: new Date(), updatedAt: new Date() },
      { id: 309, name: 'KAPUAS HULU', provinceId: 17, createdAt: new Date(), updatedAt: new Date() },
      { id: 310, name: 'KAYONG UTARA', provinceId: 17, createdAt: new Date(), updatedAt: new Date() },
      { id: 311, name: 'KETAPANG', provinceId: 17, createdAt: new Date(), updatedAt: new Date() },
      { id: 312, name: 'KOTA PONTIANAK', provinceId: 17, createdAt: new Date(), updatedAt: new Date() },
      { id: 313, name: 'KUBU RAYA', provinceId: 17, createdAt: new Date(), updatedAt: new Date() },
      { id: 314, name: 'LANDAK', provinceId: 17, createdAt: new Date(), updatedAt: new Date() },
      { id: 315, name: 'MELAWI', provinceId: 17, createdAt: new Date(), updatedAt: new Date() },
      { id: 316, name: 'MEMPAWAH', provinceId: 17, createdAt: new Date(), updatedAt: new Date() },
      { id: 317, name: 'SAMBAS', provinceId: 17, createdAt: new Date(), updatedAt: new Date() },
      { id: 318, name: 'SANGGAU', provinceId: 17, createdAt: new Date(), updatedAt: new Date() },
      { id: 319, name: 'SEKADAU', provinceId: 17, createdAt: new Date(), updatedAt: new Date() },
      { id: 320, name: 'SINGKAWANG', provinceId: 17, createdAt: new Date(), updatedAt: new Date() },
      { id: 321, name: 'SINTANG', provinceId: 17, createdAt: new Date(), updatedAt: new Date() },
      { id: 322, name: 'BALANGAN', provinceId: 18, createdAt: new Date(), updatedAt: new Date() },
      { id: 323, name: 'BANJAR', provinceId: 18, createdAt: new Date(), updatedAt: new Date() },
      { id: 324, name: 'BANJAR BARU', provinceId: 18, createdAt: new Date(), updatedAt: new Date() },
      { id: 325, name: 'BANJARMASIN', provinceId: 18, createdAt: new Date(), updatedAt: new Date() },
      { id: 326, name: 'BARITO KUALA', provinceId: 18, createdAt: new Date(), updatedAt: new Date() },
      { id: 327, name: 'HULU SUNGAI SELATAN', provinceId: 18, createdAt: new Date(), updatedAt: new Date() },
      { id: 328, name: 'HULU SUNGAI TENGAH', provinceId: 18, createdAt: new Date(), updatedAt: new Date() },
      { id: 329, name: 'HULU SUNGAI UTARA', provinceId: 18, createdAt: new Date(), updatedAt: new Date() },
      { id: 330, name: 'KOTA BARU', provinceId: 18, createdAt: new Date(), updatedAt: new Date() },
      { id: 331, name: 'TABALONG', provinceId: 18, createdAt: new Date(), updatedAt: new Date() },
      { id: 332, name: 'TANAH BUMBU', provinceId: 18, createdAt: new Date(), updatedAt: new Date() },
      { id: 333, name: 'TANAH LAUT', provinceId: 18, createdAt: new Date(), updatedAt: new Date() },
      { id: 334, name: 'TAPIN', provinceId: 18, createdAt: new Date(), updatedAt: new Date() },
      { id: 335, name: 'BARITO SELATAN', provinceId: 19, createdAt: new Date(), updatedAt: new Date() },
      { id: 336, name: 'BARITO TIMUR', provinceId: 19, createdAt: new Date(), updatedAt: new Date() },
      { id: 337, name: 'BARITO UTARA', provinceId: 19, createdAt: new Date(), updatedAt: new Date() },
      { id: 338, name: 'GUNUNG MAS', provinceId: 19, createdAt: new Date(), updatedAt: new Date() },
      { id: 339, name: 'KAPUAS', provinceId: 19, createdAt: new Date(), updatedAt: new Date() },
      { id: 340, name: 'KATINGAN', provinceId: 19, createdAt: new Date(), updatedAt: new Date() },
      { id: 341, name: 'KOTAWARINGIN BARAT', provinceId: 19, createdAt: new Date(), updatedAt: new Date() },
      { id: 342, name: 'KOTAWARINGIN TIMUR', provinceId: 19, createdAt: new Date(), updatedAt: new Date() },
      { id: 343, name: 'LAMANDAU', provinceId: 19, createdAt: new Date(), updatedAt: new Date() },
      { id: 344, name: 'MURUNG RAYA', provinceId: 19, createdAt: new Date(), updatedAt: new Date() },
      { id: 345, name: 'PALANGKA RAYA', provinceId: 19, createdAt: new Date(), updatedAt: new Date() },
      { id: 346, name: 'PULANG PISAU', provinceId: 19, createdAt: new Date(), updatedAt: new Date() },
      { id: 347, name: 'SERUYAN', provinceId: 19, createdAt: new Date(), updatedAt: new Date() },
      { id: 348, name: 'SUKAMARA', provinceId: 19, createdAt: new Date(), updatedAt: new Date() },
      { id: 349, name: 'BALIKPAPAN', provinceId: 20, createdAt: new Date(), updatedAt: new Date() },
      { id: 350, name: 'BERAU', provinceId: 20, createdAt: new Date(), updatedAt: new Date() },
      { id: 351, name: 'BONTANG', provinceId: 20, createdAt: new Date(), updatedAt: new Date() },
      { id: 352, name: 'KUTAI BARAT', provinceId: 20, createdAt: new Date(), updatedAt: new Date() },
      { id: 353, name: 'KUTAI KARTANEGARA', provinceId: 20, createdAt: new Date(), updatedAt: new Date() },
      { id: 354, name: 'KUTAI TIMUR', provinceId: 20, createdAt: new Date(), updatedAt: new Date() },
      { id: 355, name: 'MAHAKAM HULU', provinceId: 20, createdAt: new Date(), updatedAt: new Date() },
      { id: 356, name: 'PASER', provinceId: 20, createdAt: new Date(), updatedAt: new Date() },
      { id: 357, name: 'PENAJAM PASER UTARA', provinceId: 20, createdAt: new Date(), updatedAt: new Date() },
      { id: 358, name: 'SAMARINDA', provinceId: 20, createdAt: new Date(), updatedAt: new Date() },
      { id: 359, name: 'BULUNGAN', provinceId: 21, createdAt: new Date(), updatedAt: new Date() },
      { id: 360, name: 'MALINAU', provinceId: 21, createdAt: new Date(), updatedAt: new Date() },
      { id: 361, name: 'NUNUKAN', provinceId: 21, createdAt: new Date(), updatedAt: new Date() },
      { id: 362, name: 'TANA TIDUNG', provinceId: 21, createdAt: new Date(), updatedAt: new Date() },
      { id: 363, name: 'TARAKAN', provinceId: 21, createdAt: new Date(), updatedAt: new Date() },
      { id: 364, name: 'BOALEMO', provinceId: 22, createdAt: new Date(), updatedAt: new Date() },
      { id: 365, name: 'BONE BOLANGO', provinceId: 22, createdAt: new Date(), updatedAt: new Date() },
      { id: 366, name: 'GORONTALO', provinceId: 22, createdAt: new Date(), updatedAt: new Date() },
      { id: 367, name: 'GORONTALO UTARA', provinceId: 22, createdAt: new Date(), updatedAt: new Date() },
      { id: 368, name: 'KOTA GORONTALO', provinceId: 22, createdAt: new Date(), updatedAt: new Date() },
      { id: 369, name: 'POHUWATO', provinceId: 22, createdAt: new Date(), updatedAt: new Date() },
      { id: 370, name: 'MAJENE', provinceId: 23, createdAt: new Date(), updatedAt: new Date() },
      { id: 371, name: 'MAMASA', provinceId: 23, createdAt: new Date(), updatedAt: new Date() },
      { id: 372, name: 'MAMUJU', provinceId: 23, createdAt: new Date(), updatedAt: new Date() },
      { id: 373, name: 'MAMUJU TENGAH', provinceId: 23, createdAt: new Date(), updatedAt: new Date() },
      { id: 374, name: 'PASANGKAYU', provinceId: 23, createdAt: new Date(), updatedAt: new Date() },
      { id: 375, name: 'POLEWALI MANDAR', provinceId: 23, createdAt: new Date(), updatedAt: new Date() },
      { id: 376, name: 'BANTAENG', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 377, name: 'BARRU', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 378, name: 'BONE', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 379, name: 'BULUKUMBA', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 380, name: 'ENREKANG', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 381, name: 'GOWA', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 382, name: 'JENEPONTO', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 383, name: 'KEPULAUAN SELAYAR', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 384, name: 'LUWU', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 385, name: 'LUWU TIMUR', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 386, name: 'LUWU UTARA', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 387, name: 'MAKASSAR', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 388, name: 'MAROS', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 389, name: 'PALOPO', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 390, name: 'PANGKAJENE DAN KEPULAUAN', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 391, name: 'PAREPARE', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 392, name: 'PINRANG', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 393, name: 'SIDENRENG RAPPANG', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 394, name: 'SINJAI', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 395, name: 'SOPPENG', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 396, name: 'TAKALAR', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 397, name: 'TANA TORAJA', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 398, name: 'TORAJA UTARA', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 399, name: 'WAJO', provinceId: 24, createdAt: new Date(), updatedAt: new Date() },
      { id: 400, name: 'BANGGAI', provinceId: 25, createdAt: new Date(), updatedAt: new Date() },
      { id: 401, name: 'BANGGAI KEPULAUAN', provinceId: 25, createdAt: new Date(), updatedAt: new Date() },
      { id: 402, name: 'BANGGAI LAUT', provinceId: 25, createdAt: new Date(), updatedAt: new Date() },
      { id: 403, name: 'BUOL', provinceId: 25, createdAt: new Date(), updatedAt: new Date() },
      { id: 404, name: 'DONGGALA', provinceId: 25, createdAt: new Date(), updatedAt: new Date() },
      { id: 405, name: 'MOROWALI', provinceId: 25, createdAt: new Date(), updatedAt: new Date() },
      { id: 406, name: 'MOROWALI UTARA', provinceId: 25, createdAt: new Date(), updatedAt: new Date() },
      { id: 407, name: 'PALU', provinceId: 25, createdAt: new Date(), updatedAt: new Date() },
      { id: 408, name: 'PARIGI MOUTONG', provinceId: 25, createdAt: new Date(), updatedAt: new Date() },
      { id: 409, name: 'POSO', provinceId: 25, createdAt: new Date(), updatedAt: new Date() },
      { id: 410, name: 'SIGI', provinceId: 25, createdAt: new Date(), updatedAt: new Date() },
      { id: 411, name: 'TOJO UNA-UNA', provinceId: 25, createdAt: new Date(), updatedAt: new Date() },
      { id: 412, name: 'TOLI-TOLI', provinceId: 25, createdAt: new Date(), updatedAt: new Date() },
      { id: 413, name: 'BAU-BAU', provinceId: 26, createdAt: new Date(), updatedAt: new Date() },
      { id: 414, name: 'BOMBANA', provinceId: 26, createdAt: new Date(), updatedAt: new Date() },
      { id: 415, name: 'BUTON', provinceId: 26, createdAt: new Date(), updatedAt: new Date() },
      { id: 416, name: 'BUTON SELATAN', provinceId: 26, createdAt: new Date(), updatedAt: new Date() },
      { id: 417, name: 'BUTON TENGAH', provinceId: 26, createdAt: new Date(), updatedAt: new Date() },
      { id: 418, name: 'BUTON UTARA', provinceId: 26, createdAt: new Date(), updatedAt: new Date() },
      { id: 419, name: 'KENDARI', provinceId: 26, createdAt: new Date(), updatedAt: new Date() },
      { id: 420, name: 'KOLAKA', provinceId: 26, createdAt: new Date(), updatedAt: new Date() },
      { id: 421, name: 'KOLAKA TIMUR', provinceId: 26, createdAt: new Date(), updatedAt: new Date() },
      { id: 422, name: 'KOLAKA UTARA', provinceId: 26, createdAt: new Date(), updatedAt: new Date() },
      { id: 423, name: 'KONAWE', provinceId: 26, createdAt: new Date(), updatedAt: new Date() },
      { id: 424, name: 'KONAWE KEPULAUAN', provinceId: 26, createdAt: new Date(), updatedAt: new Date() },
      { id: 425, name: 'KONAWE SELATAN', provinceId: 26, createdAt: new Date(), updatedAt: new Date() },
      { id: 426, name: 'KONAWE UTARA', provinceId: 26, createdAt: new Date(), updatedAt: new Date() },
      { id: 427, name: 'MUNA', provinceId: 26, createdAt: new Date(), updatedAt: new Date() },
      { id: 428, name: 'MUNA BARAT', provinceId: 26, createdAt: new Date(), updatedAt: new Date() },
      { id: 429, name: 'WAKATOBI', provinceId: 26, createdAt: new Date(), updatedAt: new Date() },
      { id: 430, name: 'BITUNG', provinceId: 27, createdAt: new Date(), updatedAt: new Date() },
      { id: 431, name: 'BOLAANG MONGONDOW', provinceId: 27, createdAt: new Date(), updatedAt: new Date() },
      { id: 432, name: 'BOLAANG MONGONDOW SELATAN', provinceId: 27, createdAt: new Date(), updatedAt: new Date() },
      { id: 433, name: 'BOLAANG MONGONDOW TIMUR', provinceId: 27, createdAt: new Date(), updatedAt: new Date() },
      { id: 434, name: 'BOLAANG MONGONDOW UTARA', provinceId: 27, createdAt: new Date(), updatedAt: new Date() },
      { id: 435, name: 'KEPULAUAN SANGIHE', provinceId: 27, createdAt: new Date(), updatedAt: new Date() },
      { id: 436, name: 'KEPULAUAN TALAUD', provinceId: 27, createdAt: new Date(), updatedAt: new Date() },
      { id: 437, name: 'KOTAMOBAGU', provinceId: 27, createdAt: new Date(), updatedAt: new Date() },
      { id: 438, name: 'MANADO', provinceId: 27, createdAt: new Date(), updatedAt: new Date() },
      { id: 439, name: 'MINAHASA', provinceId: 27, createdAt: new Date(), updatedAt: new Date() },
      { id: 440, name: 'MINAHASA SELATAN', provinceId: 27, createdAt: new Date(), updatedAt: new Date() },
      { id: 441, name: 'MINAHASA TENGGARA', provinceId: 27, createdAt: new Date(), updatedAt: new Date() },
      { id: 442, name: 'MINAHASA UTARA', provinceId: 27, createdAt: new Date(), updatedAt: new Date() },
      { id: 443, name: 'SIAU TAGULANDANG BIARO', provinceId: 27, createdAt: new Date(), updatedAt: new Date() },
      { id: 444, name: 'TOMOHON', provinceId: 27, createdAt: new Date(), updatedAt: new Date() },
      { id: 445, name: 'BADUNG', provinceId: 28, createdAt: new Date(), updatedAt: new Date() },
      { id: 446, name: 'DENPASAR', provinceId: 28, createdAt: new Date(), updatedAt: new Date() },
      { id: 447, name: 'BANGLI', provinceId: 28, createdAt: new Date(), updatedAt: new Date() },
      { id: 448, name: 'BULELENG', provinceId: 28, createdAt: new Date(), updatedAt: new Date() },
      { id: 449, name: 'GIANYAR', provinceId: 28, createdAt: new Date(), updatedAt: new Date() },
      { id: 450, name: 'JEMBRANA', provinceId: 28, createdAt: new Date(), updatedAt: new Date() },
      { id: 451, name: 'KARANGASEM', provinceId: 28, createdAt: new Date(), updatedAt: new Date() },
      { id: 452, name: 'KLUNGKUNG', provinceId: 28, createdAt: new Date(), updatedAt: new Date() },
      { id: 453, name: 'TABANAN', provinceId: 28, createdAt: new Date(), updatedAt: new Date() },
      { id: 454, name: 'BIMA', provinceId: 29, createdAt: new Date(), updatedAt: new Date() },
      { id: 455, name: 'DOMPU', provinceId: 29, createdAt: new Date(), updatedAt: new Date() },
      { id: 456, name: 'LOMBOK BARAT', provinceId: 29, createdAt: new Date(), updatedAt: new Date() },
      { id: 457, name: 'LOMBOK TENGAH', provinceId: 29, createdAt: new Date(), updatedAt: new Date() },
      { id: 458, name: 'LOMBOK TIMUR', provinceId: 29, createdAt: new Date(), updatedAt: new Date() },
      { id: 459, name: 'LOMBOK UTARA', provinceId: 29, createdAt: new Date(), updatedAt: new Date() },
      { id: 460, name: 'MATARAM', provinceId: 29, createdAt: new Date(), updatedAt: new Date() },
      { id: 461, name: 'SUMBAWA', provinceId: 29, createdAt: new Date(), updatedAt: new Date() },
      { id: 462, name: 'SUMBAWA BARAT', provinceId: 29, createdAt: new Date(), updatedAt: new Date() },
      { id: 463, name: 'ALOR', provinceId: 30, createdAt: new Date(), updatedAt: new Date() },
      { id: 464, name: 'BELU', provinceId: 30, createdAt: new Date(), updatedAt: new Date() },
      { id: 465, name: 'ENDE', provinceId: 30, createdAt: new Date(), updatedAt: new Date() },
      { id: 466, name: 'FLORES TIMUR', provinceId: 30, createdAt: new Date(), updatedAt: new Date() },
      { id: 467, name: 'KUPANG', provinceId: 30, createdAt: new Date(), updatedAt: new Date() },
      { id: 468, name: 'LEMBATA', provinceId: 30, createdAt: new Date(), updatedAt: new Date() },
      { id: 469, name: 'MALAKA', provinceId: 30, createdAt: new Date(), updatedAt: new Date() },
      { id: 470, name: 'MANGGARAI', provinceId: 30, createdAt: new Date(), updatedAt: new Date() },
      { id: 471, name: 'MANGGARAI BARAT', provinceId: 30, createdAt: new Date(), updatedAt: new Date() },
      { id: 472, name: 'MANGGARAI TIMUR', provinceId: 30, createdAt: new Date(), updatedAt: new Date() },
      { id: 473, name: 'NAGEKEO', provinceId: 30, createdAt: new Date(), updatedAt: new Date() },
      { id: 474, name: 'NGADA', provinceId: 30, createdAt: new Date(), updatedAt: new Date() },
      { id: 475, name: 'ROTE NDAO', provinceId: 30, createdAt: new Date(), updatedAt: new Date() },
      { id: 476, name: 'SABU RAIJUA', provinceId: 30, createdAt: new Date(), updatedAt: new Date() },
      { id: 477, name: 'SIKKA', provinceId: 30, createdAt: new Date(), updatedAt: new Date() },
      { id: 478, name: 'SUMBA BARAT', provinceId: 30, createdAt: new Date(), updatedAt: new Date() },
      { id: 479, name: 'SUMBA BARAT DAYA', provinceId: 30, createdAt: new Date(), updatedAt: new Date() },
      { id: 480, name: 'SUMBA TENGAH', provinceId: 30, createdAt: new Date(), updatedAt: new Date() },
      { id: 481, name: 'SUMBA TIMUR', provinceId: 30, createdAt: new Date(), updatedAt: new Date() },
      { id: 482, name: 'TIMOR TENGAH SELATAN', provinceId: 30, createdAt: new Date(), updatedAt: new Date() },
      { id: 483, name: 'TIMOR TENGAH UTARA', provinceId: 30, createdAt: new Date(), updatedAt: new Date() },
      { id: 484, name: 'AMBON', provinceId: 31, createdAt: new Date(), updatedAt: new Date() },
      { id: 485, name: 'BURU', provinceId: 31, createdAt: new Date(), updatedAt: new Date() },
      { id: 486, name: 'BURU SELATAN', provinceId: 31, createdAt: new Date(), updatedAt: new Date() },
      { id: 487, name: 'KEP. ARU', provinceId: 31, createdAt: new Date(), updatedAt: new Date() },
      { id: 488, name: 'MALUKU BARAT DAYA', provinceId: 31, createdAt: new Date(), updatedAt: new Date() },
      { id: 489, name: 'MALUKU TENGAH', provinceId: 31, createdAt: new Date(), updatedAt: new Date() },
      { id: 490, name: 'MALUKU TENGGARA', provinceId: 31, createdAt: new Date(), updatedAt: new Date() },
      { id: 491, name: 'MALUKU TENGGARA BARAT', provinceId: 31, createdAt: new Date(), updatedAt: new Date() },
      { id: 492, name: 'SERAM BAG. BARAT', provinceId: 31, createdAt: new Date(), updatedAt: new Date() },
      { id: 493, name: 'SERAM BAG. TIMUR', provinceId: 31, createdAt: new Date(), updatedAt: new Date() },
      { id: 494, name: 'TUAL', provinceId: 31, createdAt: new Date(), updatedAt: new Date() },
      { id: 495, name: 'HALMAHERA BARAT', provinceId: 32, createdAt: new Date(), updatedAt: new Date() },
      { id: 496, name: 'HALMAHERA SELATAN', provinceId: 32, createdAt: new Date(), updatedAt: new Date() },
      { id: 497, name: 'HALMAHERA TENGAH', provinceId: 32, createdAt: new Date(), updatedAt: new Date() },
      { id: 498, name: 'HALMAHERA TIMUR', provinceId: 32, createdAt: new Date(), updatedAt: new Date() },
      { id: 499, name: 'HALMAHERA UTARA', provinceId: 32, createdAt: new Date(), updatedAt: new Date() },
      { id: 500, name: 'KEPULAUAN SULA', provinceId: 32, createdAt: new Date(), updatedAt: new Date() },
      { id: 501, name: 'PULAU MOROTAI', provinceId: 32, createdAt: new Date(), updatedAt: new Date() },
      { id: 502, name: 'PULAU TALIABU', provinceId: 32, createdAt: new Date(), updatedAt: new Date() },
      { id: 503, name: 'TERNATE', provinceId: 32, createdAt: new Date(), updatedAt: new Date() },
      { id: 504, name: 'TIDORE KEPULAUAN', provinceId: 32, createdAt: new Date(), updatedAt: new Date() },
      { id: 505, name: 'ASMAT', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 506, name: 'BIAK NUMFOR', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 507, name: 'BOVEN DIGOEL', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 508, name: 'DIEYAI', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 509, name: 'DOGIYAI', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 510, name: 'INTAN JAYA', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 511, name: 'JAYAPURA', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 512, name: 'JAYAWIJAYA', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 513, name: 'KEEROM', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 514, name: 'KEP. YAPEN', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 515, name: 'LANNY JAYA', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 516, name: 'MAMBERAMO RAYA', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 517, name: 'MAMBERAMO TENGAH', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 518, name: 'MAPPI', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 519, name: 'MERAUKE', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 520, name: 'MIMIKA', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 521, name: 'NABIRE', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 522, name: 'NDUGA', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 523, name: 'PANIAI', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 524, name: 'PEGUNANGAN BINTANG', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 525, name: 'PUNCAK', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 526, name: 'PUNCAK JAYA', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 527, name: 'SARMI', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 528, name: 'SUPIORI', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 529, name: 'TOLIKARA', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 530, name: 'WAROPEN', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 531, name: 'YAHUKIMO', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 532, name: 'YALIMO', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
      { id: 533, name: 'FAKFAK', provinceId: 34, createdAt: new Date(), updatedAt: new Date() },
      { id: 534, name: 'KAIMANA', provinceId: 34, createdAt: new Date(), updatedAt: new Date() },
      { id: 535, name: 'KOTA SORONG', provinceId: 34, createdAt: new Date(), updatedAt: new Date() },
      { id: 536, name: 'MANOKWARI', provinceId: 34, createdAt: new Date(), updatedAt: new Date() },
      { id: 537, name: 'MANOKWARI SELATAN', provinceId: 34, createdAt: new Date(), updatedAt: new Date() },
      { id: 538, name: 'MAYBRAT', provinceId: 34, createdAt: new Date(), updatedAt: new Date() },
      { id: 539, name: 'PEGUNUNGAN ARFAK', provinceId: 34, createdAt: new Date(), updatedAt: new Date() },
      { id: 540, name: 'RAJA AMPAT', provinceId: 34, createdAt: new Date(), updatedAt: new Date() },
      { id: 541, name: 'SORONG', provinceId: 34, createdAt: new Date(), updatedAt: new Date() },
      { id: 542, name: 'SORONG SELATAN', provinceId: 34, createdAt: new Date(), updatedAt: new Date() },
      { id: 543, name: 'TAMBRAUW', provinceId: 34, createdAt: new Date(), updatedAt: new Date() },
      { id: 544, name: 'TELUK BINTUNI', provinceId: 34, createdAt: new Date(), updatedAt: new Date() },
      { id: 545, name: 'TELUK WONDAMA', provinceId: 34, createdAt: new Date(), updatedAt: new Date() },
      { id: 22132, name: 'KOTA JAYAPURA', provinceId: 33, createdAt: new Date(), updatedAt: new Date() },
    ], {});
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Provinces', null, {});
  }
};
